In [1]:
import torch

device = 'cpu'
# Create tensor A with shape (3, 2)
A = torch.randn(3, 2)

# Create tensor B with shape (2, 3)
B = torch.randn(2, 3)

# Print tensors
print("Tensor A:")
print(A)
print("Tensor B:")
print(B)


Tensor A:
tensor([[-0.6506,  0.5898],
        [ 1.0993,  0.8082],
        [-0.4500, -0.0801]])
Tensor B:
tensor([[ 0.8016,  1.2751,  1.6066],
        [ 0.9922, -0.0397,  0.3606]])


In [2]:
# Matrix multiplication: A (3x2) @ B (2x3) = C (3x3)
C = A @ B

print("Matrix Multiplication C = A @ B:")
print(C)


Matrix Multiplication C = A @ B:
tensor([[ 0.0637, -0.8530, -0.8326],
        [ 1.6830,  1.3697,  2.0576],
        [-0.4402, -0.5706, -0.7519]])


In [3]:
# Element-wise addition: D = A + tensor of ones with same shape as A
D = A + torch.ones_like(A)

print("Element-wise Addition D = A + 1:")
print(D)


Element-wise Addition D = A + 1:
tensor([[0.3494, 1.5898],
        [2.0993, 1.8082],
        [0.5500, 0.9199]])


In [4]:
# Move tensor C to device (GPU if available, else CPU)
C_device = C.to(device)

print("C moved to device:", C_device.device)
print(C_device)


C moved to device: cpu
tensor([[ 0.0637, -0.8530, -0.8326],
        [ 1.6830,  1.3697,  2.0576],
        [-0.4402, -0.5706, -0.7519]])
